### ISSUE TITLE
When setting up default example widget not found

### ISSUE THREAD

**Issue by facultymatt** [jenssegers/codeigniter-template-library#3]
I get the error `Widget 'hero_widget' was not found.` when trying to run the demo. I have put the widgets folder inside the application folder, and set up everything else as described. Any ideas?

Seems that `_widget_path` is not being set in 

```
 /**
     * Initialize with configuration array
     * @param array $config
     * @return Template
     */
    public function initialize($config = array()) {
        foreach ($config as $key => $val) {
            $this->{'_' . $key} = $val;
        }

        if ($this->_widget_path == '') {
            $this->_widget_path = APPPATH . 'widgets/';
        }

        if ($this->_parser && !class_exists('CI_Parser')) {
            $this->_ci->load->library('parser');
        }
    }
```

**Comment by enlivenapp** [comment]
I had the same problem as facultymatt and traced the error to the same conclusion.  Unfortunately, the author provides no support for any of his work  that I've seen.  :(

**Comment by jenssegers** [comment]
I am unable to reproduce this error. What version of Codeigniter are you using?

**Comment by spaceemotion** [comment]
For me the demo worked just as advertised - no problems (using latest 2.1.3 version).

**Comment by enlivenapp** [comment]
I'm using CI 2.1.3
MAMP v2.1.1. 
PHP v5.4.4.

Same issue on linux box (Ubuntu/Mint) LAMP
CI 2.1.3
PHP 5.3

**Comment by spaceemotion** [comment]
I just used a clean install and copied the correct files over to their defined destination (I am using XAMPP on a Mac, running PHP 5.3). Are you sure you also copied the configuration files (I think there was a widget path var)?

**Comment by jenssegers** [comment]
Did you copy the application/widgets folder?

**Comment by enlivenapp** [comment]
spaceemotion,

Even if the application/widgets files isn't there, the global APPPATH isn't being set for for _widget_path in /library/Template.php

so the library sets _widget_path to ~/widgets instead of ~/application/widgets  (around line 65)

sergersjens:
I did, yes.  Installed with sparks and without sparks.

**Comment by jenssegers** [comment]
@wbc-mike, it seems that your config is not being loaded.

But nevertheless, you are right about the widget_path issue. If added a fix in 44d9e3d

**Comment by enlivenapp** [comment]
segersjens,

Thanks for the fix and looking into this.  I'm applying that now.

Also, thanks for the template.  It works great with the CMS I'm building.

**Comment by jenssegers** [comment]
@wbc-mike the demo template is based on Twitter's Boostrap. I am replacing the demo with a newer version as we speak.

**Comment by enlivenapp** [comment]
segersjens,

Reporting back,  It's working 100% now.  
DEBUG - 2012-12-13 22:12:28 --> Widget Path: application/widgets/

on line 185 (after the fix) I wrote in:
    public function widget($name, $data = array()) {
        $class = str_replace('.php', '', trim($name, '/'));
        log_message('debug', 'Widget Path: '. $this->_widget_path); // this new line

Everything loads perfectly now.

Thanks again and I'll keep an eye out for the newer version.

**Comment by jenssegers** [comment]
I just pushed the new version, let me know what you think.

**Comment by enlivenapp** [comment]
@segersjens 

Really nice.  It gives more hints how to use it fully.

Thanks
